export const OBTENER10OPERACIONES = 'OBTENER10OPERACIONES';
export const OBTENEROPERACIONES = 'OBTENEROPERACIONES';
export const SELECCIONAROPERACION = 'SELECCIONAROPERACION';
export const ELIMINAROPERACION = 'ELIMINAROPERACION';
export const CREAROPERACION = 'CREAROPERACION';
export const OBTENERBALANCE = 'OBTENERBALANCE';
export const OBTENERCATEGORIAS = 'OBTENERCATEGORIAS';

export const MOSTRARALERTA = 'MOSTRARALERTA'
export const OCULTARALERTA = 'OCULTARALERTA';
